### ISSUE TITLE
Set Channelname as title

### ISSUE THREAD

**Issue by AlBundy33** [rsiebert/TVHClient#203]
Currently MX Player shows a large number as title. 

It would be nice to see the name of the running channel (maybe with number). 

Afaik MX Player and maybe VLC supporting "title" as extra-parameter.

**Comment by Ragamuffin85** [comment]
Nice feature.
I would appreciate it

But I'm afraid, that there have to be implemented a workaround for every single Player.

Due to the fact, that the used "Intent"-class can be configured with the putExtra-Method.

The title in VLC can be set with
i.putExtra("itemTitle", "I'm a video title");

MX Player instead uses
i.putExtra("title", "I'm a video title");

This kind of workaround is not very generic and degrades the maintainability.

If anybody knows a more generic way - instead if the putExtra-Method - I would be grateful to hear about it and for Robert it could be useful either ;-).

Best regards

**Comment by rsiebert** [comment]
I can at least add these two extras to the intent. Maybe other players use the same string.

**Comment by AlBundy33** [comment]
This sounds good for me.
