### ISSUE TITLE
Problem with ststus recordings

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#232]
Hi
I found an issue. WHen i click to record programms and programms start recording. Then i click cancel recording this programms , and have info that recording was canceled but still show that is now recording. When i close app TVHClient and open again ststus this programm is ok and now not show icon thqat this program is recording. But i must close app.

But in dailed recording i dont see this cancel recording but when i go to web ui Failed recordings i see this programm.

**Comment by rsiebert** [comment]
Relates to #233

**Comment by rsiebert** [comment]
Fixed in https://github.com/rsiebert/TVHClient/commit/7cc467534383996634b789c81a2dccc61e972ad9

**Comment by ghost** [comment]
problem not resolved

**Comment by rsiebert** [comment]
Here is what I did:
In the channel list I long press on a program and select record from the menu, the recording icon is shown. Also the recording is shown in the scheduled recording screen. I long press on the same program in the channel list and select cancel from the menu. The recording icon disappears. The recording is not shown in the scheduled recording screen. It is now in the failed recording screen. So this is expected behaviour and ok.

**Comment by ghost** [comment]
But disapear is long wait... Is not refresh when i click on CANCEL recording. Refresh after about 2-5 sec.

**Comment by ghost** [comment]
And good option will be add to user can stop recording and mark it as success recording. Now is mark as FAILED. This option is available by GUI TVheadend.

**Comment by rsiebert** [comment]
The app sends the cancel request and the server answers. This can take a few seconds. It depends on the server how fast it can stop the recording. So that is ok that it takes 1-5 sec. The server also decides if the recording is marked as failed or completed. See [here].(https://github.com/rsiebert/TVHClient/blob/develop/app/src/main/java/org/tvheadend/tvhclient/TVHClientApplication.java#L527)

**Comment by ghost** [comment]
But in webgui when i manual stop it mark as finished success. But when i cancel this mark as failed.

**Comment by rsiebert** [comment]
The [method to stop recordings](https://github.com/tvheadend/tvheadend/commit/b1e89e6f36fe75104cb9785cfab7e7e0f347e13c#diff-bb110a0c4c00627cea894e60917a86e8) has been added on 9.2.2016. If your server supports API version 25 you can use this method with the new beta.

**Comment by ghost** [comment]
No my server support api 23. I wait for update my server and test it. Butr beta TVHBlient is available in Google Play ?

**Comment by ghost** [comment]
Did you recived my email with info about logo ?
14.05.2016 08:17 "Robert Siebert" notifications@github.com napisał(a):

**Comment by ghost** [comment]
Are you sure that tvheadend support API version 25 ?

**Comment by rsiebert** [comment]
Yes, check out the [source code](https://github.com/tvheadend/tvheadend/blob/b1e89e6f36fe75104cb9785cfab7e7e0f347e13c/src/htsp_server.c#L69). There you see at line 69: API version 25.

**Comment by ghost** [comment]
But how i can check it on my server ?

**Comment by rsiebert** [comment]
Check the TVHClient status screen. There you see the server API version at the bottom.

**Comment by ghost** [comment]
Is ok i have version 25.
16.05.2016 09:05 "Robert Siebert" notifications@github.com napisał(a):
