### ISSUE TITLE
Offline EPG

### ISSUE THREAD

**Issue by bigbig6** [rsiebert/TVHClient#250]
Hi,

when I'm not connected to TVHE (mainly because I'm not at home), TVHClient try to connect itself but show nothing.

It would be great that we can see the EPG and other informations, basicaly by caching them on the client.

Thank's

**Comment by rsiebert** [comment]
Caching the information would be a bigger task without much gain for the majority of the users. You could connect to your server via VPN. Then you get the epg data.

**Comment by bigbig6** [comment]
Hi,

I don't want to have a VPN my system isn't open, and I'm not sure that I'm alone to want a offline EPG

Caching information is not so hard...

Big

Date: Wed, 20 Jul 2016 07:14:45 -0700

**Comment by bigbig6** [comment]
It's hard to close a workitem like that, without discussing about it...

Make a poll, and if nobody want it, close it.

Date: Wed, 20 Jul 2016 07:52:50 -0700

**Comment by rsiebert** [comment]
I reopen the issue just to see the results. Please open a poll. I don't know if github is the right place or google+. There was a poll for a new icon. Other than that even if a few people request the feature it is no guarantee that I will implement the feature. I do this voluntarily and if there is time to do so.

If it is not hard then please provide patches. The main issue is time.
Other than what is the benefit of just looking at the EPG if you cant schedule new recordings while being offline? No option to remember the newly added recordings and later inform the server when a connection is available?

As a first thought the following stuff would be required
- Define a database structure so that all information for an epg event is stored
- Check cache against incoming data, add new or update exising entries
- Add loader classes in the channel, program and program list fragments so that fetching stuff from the database does not block the ui thread
- Add database / cache rotation and options to define how much data we want to save. ability to see the past?
  ...

**Comment by bigbig6** [comment]
Thank's for reopening this.

I know time is the main problem, I do some translations, and it take a lot of time.

Offline EPG is the first part, it seems for me interesting to be able to view programs every where even if I'm not connected. I will try to make a poll, I don't know where for the moment. I hope some other people would be interested in.

A second part would be to schedule some recording if needed. When the system will be connected, syncing all of these informations.

seeing the past? for checking what we missed, that's a good idea too..

**Comment by bigbig6** [comment]
Hello,

Should be possible to use XML files in order to cache some informations?
A sync can be do when connected, and you can have some days in the past...

One file per day, and you update file(s) if any changes were done.

**Comment by rsiebert** [comment]
The new version 2.0.0 will use a database to cache the epg data.

**Comment by bigbig6** [comment]
Hi, thank's, it sound really good!

When this version will be available?

Big

**Comment by rsiebert** [comment]
This is available in  the new 2.0.0 version.
