### ISSUE TITLE
Press on "STOP" in running recording calls playback

### ISSUE THREAD

**Issue by hurzl** [rsiebert/TVHClient#265]
and does not stop the recording.

**Comment by rsiebert** [comment]
I have checked my setting here, can't see the issue, so I need more info.
In which screen does this happen? Channel list? Scheduled recording list? Program guide?
Phone or tablet?

**Comment by hurzl** [comment]
running recordings as I said

**Comment by rsiebert** [comment]
Etwas mehr Info brauche ich schon als nur "running recording"

There is no screen running recordings. Only completed, scheduled, timer and failed recordings. then the program guide screen, program list and channel screens. In some of those a recording can be displayed as running. When I stop a running recording in the scheduled screen the recording will be stopped, not played. So I need a little bit more info to find the issue.

**Comment by hurzl** [comment]
unter "geplante Aufnahmen" fehlt der Wiedergabeknopf, STOPPEN startet Wiedergabe

**Comment by rsiebert** [comment]
Thanks, that was the missing information. Should be fixed now in https://github.com/rsiebert/TVHClient/commit/c38475423d9fbb7df862a570169c27aa28cf2744

**Comment by hurzl** [comment]
Gibt's auch ein Update und/oder warum geht das importieren in android studio nicht?

**Comment by rsiebert** [comment]
Update gibts bald.
Was kommt denn für ein Fehler? Sourcen von github runterladen, entpacken
und das Projekt mit Android Studio öffnen klappt nicht?

hurzl notifications@github.com schrieb am Sa., 1. Okt. 2016, 16:33:

Gibt's auch ein Update und/oder warum geht das importieren in android
studio nicht?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/rsiebert/TVHClient/issues/265#issuecomment-250915471,
or mute the thread

**Comment by hurzl** [comment]
> Sourcen von github runterladen, entpacken und das Projekt mit Android Studio öffnen klappt nicht?

doch jetzt ging es ...
