### ISSUE TITLE
Allow https access

### ISSUE THREAD

**Issue by 3DJupp** [rsiebert/TVHClient#269]
It should be possible to have access via https. 
I got a reverse proxy (nginx) running, but can't find a way to use it with the tvhclient. The reverse proxy handles internal and external requests. 
It works with my browser, so there should be an option to use it in the app. 

Manually setting the port to 443 does not work. 
Authentication is still done via TV Headend, but I might use nginx for authentication soon. 

Nginx in general is working great, there are a few devices which can't be forwarded so easily, most of them are using cgi or lua scripts. TVH does not use any of them.

**Comment by rsiebert** [comment]
I don't have a reverse proxy at home to test this functionality. I could implement this if I could get a guest access or someone is able to test or provides patches.

**Comment by githubsean** [comment]
I have the exact same issue/request.
I also use nginx reverse proxying and encrypting the connection.
I'm happy to set up a test account for you.

**Comment by rsiebert** [comment]
That would be great

**Comment by 3DJupp** [comment]
I can also create an account for testing, how can we interact regarding the
details?

Robert Siebert notifications@github.com schrieb am Mo., 7. Nov. 2016,
10:40:

**Comment by rsiebert** [comment]
You can mail me the details to rsiebert80@gmail.com

**Comment by githubsean** [comment]
Details sent

**Comment by rsiebert** [comment]
As I understood the setting for most users using a reverse proxy is that only port 9982 will be forwarded to the outside port 443. This is only the webinterface of the tvheadend server. This is not sufficient because the app communicates via port 9981 and playing of recordings is done via port 9982. So both ports need to be forwarded. Anyone with this setup that I can use for testing?

**Comment by dkonerma** [comment]
Hi Robert,

I'm using a an https reverse proxy (apache httpd), with addtl. tvheadend config  --http_root /tvh, my server is exposed as something like https://myserver.com/tvh.

So I would very much welcome to have the tvhclient http host/port config being replaced by a general http url setting where one could enter the complete https://myserver.com/tvh. This would solve all in one. ;-). You could put in a self-explaining default so that people understand what is required (e.g. http://myserver.com:9981).

BTW, yes. My server's port 9982 is also exposed to the internet, so I can create you an account to test with that.

Best regards
DIetmar.

PS, to make it clear. ;-)
I forward the http port 9981 to external :443/https.
The HTSP port 9982 with it's digest authentication is forwarded "as is".

**Comment by der-andy** [comment]
+1 for this feature. I also use an HTTPS reverse proxy to access Tvheadend from the outside (IIS in my case). Personally, I don't need to watch TV or recordings when I'm not at home, so port 9982 is currently kept closed.

I haven't really looked into your code and fear that this might be a bit more than just replacing `http` with `https` at one point, especially if someone wants to use a self-signed certificate. But I would love to be able to use the app without having to establish a VPN connection first (which works perfectly, by the way).

**Comment by 3DJupp** [comment]
I can confirm, that http forwarding and an exposed port 9982 is working right now. 
But there should be a check box with 'https'  or something similar. I checked the URL when clicking at the play button. It says http://user:pass@host:443 (which does not make that much sense, but I can change the port to the http one.)

**Comment by dkonerma** [comment]
Hi Robert,

any plans to implement this? Would be very much appreciated.  ;-)

Thx 
Dietmar.

**Comment by rsiebert** [comment]
I have currently little time to continue working on the app but I plan to add this.
I dont know if it is sufficient to add a https checkbox to the connection settings and allow accepting self signed/all certificates.

**Comment by dkonerma** [comment]
Robert,
I personally would prefer a single URL config value, that would allow to define proto, host, port, uri all in once. Maybe an additional check box "disable certificate verification". However, these day anyone should be able to install an official letsencrypt cert for free.

Thanks
Dietmar.

**Comment by VorasLT** [comment]
Hi all. 
I have same issue. Using nginx and forwarding 9981 port to https 443, 9982 port is exposed directly.
On iOS everything ok, but on android not working. App taking 443 as port not as https and MX Player or VLC doesn't understand it.

**Comment by jussisallinen** [comment]
Any estimate for this?

**Comment by CV8R** [comment]
I too require the same functionality.  Revers proxy via (nginx) running using an official letsencrypt cert.

https://myserver.com/tvh

I created an issue for the webroot but will close it now given this existing issue is open.

**Comment by CV8R** [comment]
Any update or plans to implement this feature? I am currently unable to use the TVH application becuase I can no longer access the secure server.

**Comment by trimethia** [comment]
+1 for this feature. I am using nginx reverse proxy to have https access with my  tvheadend backend.

**Comment by CV8R** [comment]
I'm looking for this feature too. However, I found that buy setting webroot to tvh and using the hostname without /tvh it works. The app doesn't allow you to add a hostname/ip address URL with name/webroot i.e. www.myserver.com/tvh

**Comment by TopperBG** [comment]
Nor to add only host name as I use too reverse proxy and my host is tvh.myhost.com without port

**Comment by dkonerma** [comment]
AFAIK recent TVHClient 2.x versions use pure HTSP (except for playback of recordings, which is lacking transcoding support... so unusable for me anyway). So I'm a happy camper currently. :-)

Casting via https would be great also, but that's something different (and trivial to add IMHO).

The next step would be enhancing HTSP to HTSPS with STARTTLS. :-) Something for the server side, of course.

Cheers
Dietmar.

**Comment by rsiebert** [comment]
The 2.x version can also use http for streaming. The external player like vlc needs to handle the given url. Casting is the same. An url is sent to the chromecast. It connects then via the url to the server and starts playing the stream (if possible).
The latest version from >= 2.2.16 can use an url like http://myserver:port.

**Comment by ManOki** [comment]
I'm not able to setup this, too.

First of all, inside the app (german version, 2.2.21), the "Server Url" contains port 9982 and the "Streaming Url" contains 9981. From my point of view, those labels must be changed, as the 9981 is the tvheadend-http port and 9982 the streaming port (https://tvheadend.org/projects/tvheadend/wiki/Install_and_initial_setup#Open-ports).

My current setup redirects the http-webinterface through apache using this configuration:

```
<Location /tvheadend>
        SSLRequireSSL
        ProxyPass http://localhost:9981/tvheadend
        ProxyPassReverse http://localhost:9981/tvheadend
        ProxyPreserveHost On
        AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE audio/x-mpegurl
        Substitute "s|http://|https://|i"
</Location>
```

I'm using the built-in basic authentification of tvheadend.

I'm able to use the built-in "Watch TV" functionality inside the browser and stream e.g. recordings via vlc using the blue "Play this stream" button, which downloads a file with the following content:

```
#EXTM3U
#EXTINF:-1,news
https://myhost.org/tvheadend/dvrfile/e78e92c6ec998732483e0e56dd9f2a1c?ticket=5812F3480EDF02166F8967CE0C9136F23C3834AD
```

So, except for the internal player of tvhclient, there is no need for streaming-port 9982?
Does tvhclient support https (e.g. LetsEncrypt)?

I tried to enter `https://myhost.org:443/tvheadend` as url, which fails authentication (shown as hint).
If i enter `https://myhost.org/tvheadend` without any port, the input is not applied to the settings.

**Comment by brimur** [comment]
Hi @rsiebert, I see you removed this as a milestone, has it been abandoned? I run my TVH server behind a reverse proxy so have been unable to use your client since then. I am currently using the Dreamplayer for TVHeadend app and it works fine through a proxy but your client works better with casting to Chromecast which I use often. Would be great if it was possible.

**Comment by dkonerma** [comment]
@brimur, I running also tvh behind a reverse proxy... and it's running perfectly fine, as TVHclient uses HTSP for all. 

What works here for me
Connection Url http://tvhserver.bla.com:9982/tvh
Playback Url http://tvhserver.bla.com:80/tvh

1) Don't ne confused... THVclient uses Server/Port in Connection Url as HTSP endpoint.

@rsiebert: that's indeed confusing as i mentioned before... I would recoomend to Name the field e.g. "HTSP server:port" and put server:9982 as default to it. It's simply not a URL. ;-)

2) If you like to use Chromecast...  the Playback Url is the one that's being used for casting. You need to configure a cast compatble streaming profile, of course. I use h264 + aac within an MKV container...  works great on all cast devices I own.

Configuring https in Playback Url still has some issue here, so I allowed *only* /tvh/stream/ with http on my reverse proxy.

@rsiebert: I see occasionally GET /tvh/imagecache/ from TVHclient in the httpd log then... maybe some left-over since this should be go through HTSP also, shouldn't it? The request has no ticket= ... so gets refused with 401 by TVH.

Cheers
Dietmar.

**Comment by brimur** [comment]
> @brimur, I running also tvh behind a reverse proxy... and it's running perfectly fine, as TVHclient uses HTSP for all.
> 
> What works here for me
> Connection Url http://tvhserver.bla.com:9982/tvh
> Playback Url http://tvhserver.bla.com:80/tvh
> 
> 1. Don't ne confused... THVclient uses Server/Port in Connection Url as HTSP endpoint.
> 
> @rsiebert: that's indeed confusing as i mentioned before... I would recoomend to Name the field e.g. "HTSP server:port" and put server:9982 as default to it. It's simply not a URL. ;-)
> 
> 1. If you like to use Chromecast...  the Playback Url is the one that's being used for casting. You need to configure a cast compatble streaming profile, of course. I use h264 + aac within an MKV container...  works great on all cast devices I own.
> 
> Configuring https in Playback Url still has some issue here, so I allowed _only_ /tvh/stream/ with http on my reverse proxy.
> 
> @rsiebert: I see occasionally GET /tvh/imagecache/ from TVHclient in the httpd log then... maybe some left-over since this should be go through HTSP also, shouldn't it? The request has no ticket= ... so gets refused with 401 by TVH.
> 
> Cheers
> Dietmar.

@dkonerma I have no issues at all accessing my TVH servers webpage externally using a browser or externally using the "dreamPlayer for TVHeadend" Android app. TVHClient however does have an issue. When I connect to the server I get an error "Authentication Failed" and cannot connect. Even if I turn off auth I still get the same "Authentication Failed" message. Right now the "dreamPlayer for TVHeadend" Android app does not allow changing profiles so its stuck with HTSP yet I can watch streams outside my home with it. TVHClient however can used different profiles so at home I can use my Chromecast profile to cast to my Chromecast with TVHClient but not with the "dreamPlayer for TVHeadend" Android app. So I was hoping this would be fixed in a future version so I can use TVHClient outside my home as well as inside.

**Comment by dkonerma** [comment]
OK, just wanted to point out that you only need to expose htsp for TVHclient. Works fine, also externally, Reverse Proxy and HTTPS are unrelated here.

**Comment by brimur** [comment]
> OK, just wanted to point out that you only need to expose htsp for TVHclient. Works fine, also externally, Reverse Proxy and HTTPS are unrelated here.

True the request is to allow https access. There was a lot of talk in the thread about reverse proxies also and the two issues were combined so I was hoping both issues were being worked on.

**Comment by ManOki** [comment]
> 
> 
> OK, just wanted to point out that you only need to expose htsp for TVHclient. Works fine, also externally, Reverse Proxy and HTTPS are unrelated here.

I think the crucial point that people ask for https is the full encryption of all connections between client (tvhclient) and server (tvheadend). But tvheadend does **not** encrypt HTSP port 9982: https://tvheadend.org/boards/5/topics/23805

To have encryption anyway, some users configured a reverse proxy to map the http-port 9981 to the encrypted webserver-port 443. But currently tvhclient depend on the htsp-port 9982 to work properly. From a user point of view, there is no need for this, as the web interface of tvheadend is able to provide all functions only via 9981/443, e.g., streaming or configure recordings.

I guess, changing this (switching from htsp-protocol to http-protocol, which might even not be supported/intented for clients by tvheadend) is a major issue resulting in a extensive rewrite of tvhclient. So far, I've found no official documentation for an http/json API by tvheadend, but only a reversed one at https://github.com/dave-p/TVH-API-docs/wiki, that only supports server version 4.3 (unstable).

**Comment by ManOki** [comment]
> I have no issues at all accessing my TVH servers webpage externally using a browser or externally using the "dreamPlayer for TVHeadend" Android app.

Even this is only possible if your tvheadend is directly available at https://myserver.tld:443. This app does also not support sub-locations at the webserver like https://myserver.tld:443/tvheadend. For reasons (inexplicable to me), most UI designer do not support a single URL-field, but only provide fields for some parts like (IPv4) address and port. Internally, an URL is build from this information anyway and even shown to the user in error messages.

**Comment by rsiebert** [comment]
As described in the [tvheadend board](https://tvheadend.org/boards/5/topics/23805) answer and in [htsp api](https://tvheadend.org/projects/tvheadend/wiki/Htsp) the password is never sent in cleartext. But if an attacker can read the traffic he still needs to decode the hts messages to get some readable data. You could also define a different htsp port in my app and you server so that at least the default port is not used. Or you could also use a VPN. Its built into Android devices. Then a reverse proxy and such is not required anymore.

Implementing the communication with the server via http and not htsp would indeed result in a large effort. There is no documentation for each release. But you can see what can be requested from the server at the bottom of [each api file](https://github.com/tvheadend/tvheadend/tree/master/src/api). You can call this in a browser and see the results. But still you would have no idea what older server would provide. The [htsp api](https://tvheadend.org/projects/tvheadend/wiki/Htsp) provides better documentation. Adding http just to drop htsp and not use 9982 because it must be exposed to the world does not provide any value or would outweight the additional effort. 

Regarding the sublocations: Because my app uses the htsp port a socket will be opened using the [InetSocketAddress](https://developer.android.com/reference/java/net/InetSocketAddress) with a hostname and port. No sublocations or whatsoever can be used there.

Regarding the single url field: The connection was specified using hostname and port separately in the past. This was changed due to issue #269 and some comments like [here](https://github.com/rsiebert/TVHClient/issues/269#issuecomment-269589342) and [here](https://github.com/rsiebert/TVHClient/issues/269#issuecomment-297758896). It also allowed greater flexibility in case http was added or something else. Currently it does not provide more value than the previous solution. It can be improved to e.g. auto add the url scheme in case its not provided.

**Comment by ManOki** [comment]
> 
> 
> Adding http just to drop htsp and not use 9982 because it must be exposed to the world does not provide any value [...]

It would make it possible that this traffic can be encrypted via https externally. That's the whole point about #269 😉 

Of course, as I wrote before, this is a major issue with a lot of subsequent effort. To reduce the effort, imho tvhclient may only support tvheadend current stable and dev versions (in the first place). However, I don't have an overview about the usage of different versions.

> 
> 
> the password is never sent in cleartext.

Yes, there is a digest solution, but this should (no longer) be considered secure. I have not found any reliable information about the hash, but so far I suspect that it is MD5 or SHA1, both of which are insecure.

> 
> 
> You could also define a different htsp port in my app and you server so that at least the default port is not used. Or you could also use a VPN. Its built into Android devices. Then a reverse proxy and such is not required anymore.

Yes, this is indeed a way to secure the traffic, but requires additional configuration on client and server side, which imho most regular users avoid.

> Regarding the single url field

My comment referred to the other app that don't use htsp but just the http(s) api. If you switch the api anyway, you can think about it right away. 😄

**Comment by rsiebert** [comment]
I have started development on the http branch. Unfortunately the http API differs.
- There is no disc space information available
- It provides string uuids instead of integer ids (main issue because the ids are used everywhere)
- no pushing of updates to the clients. I guess the app has to poll every x seconds?
- no option to request all data from the server via a single call
Just as an update.

**Comment by gamersalpha** [comment]
HEllo, do u have some news to get HTTPS on TVHCLIENT please

**Comment by Akruidenberg** [comment]
same here

**Comment by susadmin** [comment]
I would very much like to get this going as well. Thanks for all the hard work

**Comment by rsiebert** [comment]
I have abondened the work on the http support for the app because a lot of features are not available which are essential for the app to work. Examples are in my last comment above.
