### ISSUE TITLE
Tags kodi EPG

### ISSUE THREAD

**Issue by alebupal** [rsiebert/TVHClient#333]
Hello in my epg in TvHeadend, I have the following tags  [COLOR orange] TEXT EXAMPLE [/COLOR] (
https://image.prntscr.com/image/dz5ka25lTDKxhGOjMf78MQ.png) so that in kodi have colors. But the application does not interpret these tags and it is ugly.
Would it be possible for the application to interpret them? 
Here the list of kodi tags: http://kodi.wiki/view/Label_Formatting

**Comment by nickiman** [comment]
Hi,
As @alebupal has mentioned in TVHClient the info has plain text without to apply the appropiate formating. That gives this aspect in all programs in the EPG:
![imagen](https://user-images.githubusercontent.com/3627902/37436580-d232a2f4-27e8-11e8-845f-c0a5945713ce.png)

Instead of this one from Kodi:
![imagen](https://user-images.githubusercontent.com/3627902/37436661-46033eaa-27e9-11e8-9596-ac3280c73cbc.png)

Would be great if could be implemented.

**Comment by JesCR** [comment]
Kodi tags support would be great!

**Comment by nickiman** [comment]
@rsiebert I would like to lend a hand to help integrate this functionality.

Maybe I could offer you .xml files with the kodi tags written on it or anything else... Feel free to contact me in case you have some need to help to speed up the integration of this function in TVHClient.

Thanks a lot.
Regards

**Comment by rsiebert** [comment]
Providing me with the xml files would be great!

**Comment by nickiman** [comment]
Hi Robert,
Mail sent to rsiebert80@gmail.com
Have you seen it?

**Comment by rsiebert** [comment]
I have added support for the tags in the newest app version [2.2.22-183](https://drive.google.com/open?id=1SQjGTnmp0_4biSjz-wYOaiZ0BdQCKaQK) Can someone test it?

**Comment by alebupal** [comment]
> I have added support for the tags in the newest app version [2.2.22-183](https://drive.google.com/open?id=1SQjGTnmp0_4biSjz-wYOaiZ0BdQCKaQK) Can someone test it?

It works perfectly, thank you very much!

https://prnt.sc/pg0l58
https://prnt.sc/pg0lnx
