### ISSUE TITLE
Crashing app as soon as I start a chromecast session

### ISSUE THREAD

**Issue by danielloader** [rsiebert/TVHClient#348]
As title, as soon as I pick a channel and start a cast - it works and displays on the TV but it then crashes the app and any attempt to restart the app just ends up with crashing while the casting is active.
If I disable the cast at the TV end and start the app again it doesn't crash.

**Comment by francoism90** [comment]
Same issue here, any update?
@rsiebert Do you need any logging?

**Comment by rsiebert** [comment]
Is this still the case with the new 2.0.0 beta?

**Comment by francoism90** [comment]
@rsiebert No, but it doesn't play any cast stream. It just launches the external mobile player instead.

**Comment by rsiebert** [comment]
I also need a debug log here.

François M. <notifications@github.com> schrieb am Sa., 6. Okt. 2018, 20:37:

**Comment by francoism90** [comment]
@rsiebert No problem, I have enabled the debug checkbox, what is the save location?

**Comment by francoism90** [comment]
@rsiebert Here it is: https://drive.google.com/open?id=1Qhfln_d_R64xaIrrbb1w3uF3wu8Ldb1W
Both the not playing internal/exo issue, only 2 profiles and when enabling Chromecast support.

**Comment by rsiebert** [comment]
Hi,
Could you change the Playback profile to htsp?
Currently it seems it is set to cast.

The casting profile should be webm... as suggested in issue 274. Or is the
cast profile similar?

François M. <notifications@github.com> schrieb am So., 7. Okt. 2018, 17:00:

**Comment by rsiebert** [comment]
When casting is enabled there should be an additional popup menu "cast" below "play". Do you see that? This will initiate the casting stuff.

**Comment by francoism90** [comment]
@rsiebert I have created a screencast, do you have an email where I can send it to? :)

**Comment by rsiebert** [comment]
Hi,
Thanks!
Yes you can use rsiebert80@gmail.com.



Am 08.10.2018 16:53 schrieb "François M." <notifications@github.com>:

@rsiebert <https://github.com/rsiebert> I have created a screencast, do you
have an email where I can send it to? :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rsiebert/TVHClient/issues/348#issuecomment-427866281>,
or mute the thread

**Comment by rsiebert** [comment]
Hi,
Now I see what you mean. This play menu is for Playback with the internal
or external player only. i have explicitly added a cast menu.this is
missing from the toolbar. When you long press on a program it should show
cast. Does this work then?
Thanks for finding this issue.

Am 08.10.2018 17:01 schrieb "Robert Siebert" <rsiebert80@gmail.com>:

Hi,
Thanks!
Yes you can use rsiebert80@gmail.com.



Am 08.10.2018 16:53 schrieb "François M." <notifications@github.com>:

@rsiebert <https://github.com/rsiebert> I have created a screencast, do you
have an email where I can send it to? :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rsiebert/TVHClient/issues/348#issuecomment-427866281>,
or mute the thread

**Comment by francoism90** [comment]
Now it works, thanks! :+1: 
Would be great if you could use a simple icon instead to start playback, instead of the need opening a menu. :)

I still have the anonymous user (*), is this still needed for Beta v2?

**Comment by rsiebert** [comment]
I have added the missing cast menu to the toolbar.
