### ISSUE TITLE
Support for streaming profile

### ISSUE THREAD

**Issue by diraimondo** [rsiebert/TVHClient#66]
The current git version supports a new streaming/recording profiles system. It's not the client that decide the transcoding parameters but it belongs to the internal configuration of tvheadend.
It would be nice to see a transition of TVHClient to the new profile-based system.

Thanks.

**Comment by mario-tux** [comment]
In the master repository I can see many commits about the support of the new profiles. Given this, I can't see any related option in TVHClient on my Nexus 4 (latest version available on the store). What's wrong?

**Comment by rsiebert** [comment]
Hi Mario,

the master repository was the source for the 1.7.0 - 1.7.2 releases. Even
with the 1.7.2 many users could not connect or still had problems that I
could not reproduce. It seems to be related to updating the htsp API. I
guess some 3.4 thvheadend server have problems with that.
So I used the 1.6.1 codebase to develop my app. I'll introduce the features
now in smaller steps.

Best regards
Robert

Mario Di Raimondo notifications@github.com schrieb am So., 15. März 2015
um 21:56 Uhr:

**Comment by rsiebert** [comment]
I have added profile support in the next version which is currently in alpha test. If you drop me a mail I can add you the list of testers.

**Comment by diraimondo** [comment]
Thank you: mario (dot) diraimondo (at) gmail (dot) com

Il giorno sab 2 mag 2015 alle ore 17:16 Robert Siebert <
notifications@github.com> ha scritto:

**Comment by rsiebert** [comment]
Hi Mario,

you should receive the alpha version in a few hours. There are some
changes, like in-app billing, profiles and trancoding settings per
connection, manual recordings, more series recording stuff, chromecast,
profiles. To unlock these featurs you need to do a test purchage, no charge
will apply.
Regarding profiles I can't really test these because my server is a
Raspberry pi. Vlc will not play any streams except the "old" ones without
transcoding.
Please report any issues so I can fix them. Thank you very much!

To get access to the beta tester group, just join the google+ community and
then open the second link one you have been added.
https://plus.google.com/communities/110795645894468189728
https://play.google.com/apps/testing/org.tvheadend.tvhclient

Best regards
Robert

Mario Di Raimondo notifications@github.com schrieb am Sa., 2. Mai 2015 um
17:54 Uhr:

**Comment by mario-tux** [comment]
I'm still not able to install the testing version: I think you should validate my request to join the G+ community. Indeed the second link doesn't work jet for me.

**Comment by rsiebert** [comment]
Sorry, i was not at home
I just accepted your request.

Mario Di Raimondo notifications@github.com schrieb am Mo., 4. Mai 2015
15:47:

**Comment by rsiebert** [comment]
Added in 1.7.7 in the search view. Requires the unlocked version of the app.
